import http from 'node:http';import crypto from 'node:crypto';
const PORT=process.env.PORT||8080,AUTH='https://rsnjkbdasrekxghevrse.supabase.co/auth/v1',MCP='https://memoryport-bridge-v2-production.up.railway.app/mcp',states=new Map();
const html=(r,s,b,h={})=>{r.writeHead(s,{'content-type':'text/html; charset=utf-8','cache-control':'no-store',...h});r.end(b)}, form=o=>new URLSearchParams(o).toString();
async function reg(uri){const r=await fetch(AUTH+'/oauth/clients/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_name:'MemoryPort Gemini Verification',redirect_uris:[uri],token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code']})});if(!r.ok)throw Error('OAuth registration failed '+r.status);return r.json()}
http.createServer(async(q,r)=>{const u=new URL(q.url,'http://x'),base='https://'+(process.env.RAILWAY_PUBLIC_DOMAIN||q.headers.host),cb=base+'/callback';
if(u.pathname==='/')return html(r,200,'<h1>MemoryPort × Gemini</h1><p>Isolated cross-AI verification. Production MemoryPort core is unchanged.</p><a href="/start">Authorize and run test</a>');
if(u.pathname==='/start'){try{const c=await reg(cb),v=crypto.randomBytes(48).toString('base64url'),ch=crypto.createHash('sha256').update(v).digest('base64url'),st=crypto.randomBytes(24).toString('base64url');states.set(st,{v,id:c.client_id,cb});const p=new URLSearchParams({response_type:'code',client_id:c.client_id,redirect_uri:cb,state:st,code_challenge:ch,code_challenge_method:'S256'});r.writeHead(302,{location:AUTH+'/oauth/authorize?'+p});return r.end()}catch(e){return html(r,500,'Start failed: '+e.message)}}
if(u.pathname==='/callback'){const st=u.searchParams.get('state'),co=u.searchParams.get('code'),x=states.get(st);states.delete(st);if(!x||!co)return html(r,400,'Invalid callback');try{const tr=await fetch(AUTH+'/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form({grant_type:'authorization_code',code:co,client_id:x.id,redirect_uri:x.cb,code_verifier:x.v})}),td=await tr.json();if(!tr.ok)throw Error('Token exchange failed '+tr.status);
const mr=await fetch(MCP,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+td.access_token},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'memoryport_get_context',arguments:{}}})}),md=await mr.json(),mem=md?.result?.structuredContent?.memories??[];if(!mr.ok||!md.result)throw Error('MemoryPort READ failed');
const k=process.env.GEMINI_API_KEY;if(!k)throw Error('Gemini key missing');const prompt='Use ONLY this MemoryPort memory. In Indonesian state the owner nickname and preferred answer style. Memory: '+JSON.stringify(mem);const gr=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':k},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]})}),gd=await gr.json();if(!gr.ok)throw Error('Gemini failed '+gr.status);const ans=(gd.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim(),safe=ans.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));return html(r,200,'<h1>Cross-AI READ PASS</h1><p>Memory rows: '+mem.length+'</p><pre>'+safe+'</pre><p>No token or API key displayed.</p>')}catch(e){return html(r,500,'Test failed: '+e.message)}}
return html(r,404,'Not found')}).listen(PORT,()=>console.log('Gemini OAuth verifier listening',PORT));