import http from 'node:http';import crypto from 'node:crypto';
const PORT=process.env.PORT||8080,AUTH='https://rsnjkbdasrekxghevrse.supabase.co/auth/v1',MCP='https://memoryport-bridge-v2-production.up.railway.app/mcp',states=new Map();
const html=(r,s,b,h={})=>{r.writeHead(s,{'content-type':'text/html; charset=utf-8','cache-control':'no-store',...h});r.end(b)},form=o=>new URLSearchParams(o).toString(),esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function reg(uri,name){const x=await fetch(AUTH+'/oauth/clients/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_name:name,redirect_uris:[uri],token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code']})});if(!x.ok)throw Error('OAuth registration failed '+x.status);return x.json()}
async function start(q,r,provider){try{const base='https://'+(process.env.RAILWAY_PUBLIC_DOMAIN||q.headers.host),cb=base+'/'+provider+'/callback',c=await reg(cb,'MemoryPort '+provider.toUpperCase()+' Verification'),v=crypto.randomBytes(48).toString('base64url'),ch=crypto.createHash('sha256').update(v).digest('base64url'),st=crypto.randomBytes(24).toString('base64url');states.set(st,{v,id:c.client_id,cb,provider});const p=new URLSearchParams({response_type:'code',client_id:c.client_id,redirect_uri:cb,state:st,code_challenge:ch,code_challenge_method:'S256'});r.writeHead(302,{location:AUTH+'/oauth/authorize?'+p});r.end()}catch(e){html(r,500,'Start failed: '+esc(e.message))}}
async function token(u){const st=u.searchParams.get('state'),co=u.searchParams.get('code'),x=states.get(st);states.delete(st);if(!x||!co)throw Error('Invalid callback');const tr=await fetch(AUTH+'/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form({grant_type:'authorization_code',code:co,client_id:x.id,redirect_uri:x.cb,code_verifier:x.v})}),td=await tr.json();if(!tr.ok)throw Error('Token exchange failed '+tr.status);return td.access_token}
async function gemini(access){const mr=await fetch(MCP,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+access},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'memoryport_get_context',arguments:{}}})}),md=await mr.json(),mem=md?.result?.structuredContent?.memories??[];if(!mr.ok||!md.result)throw Error('MemoryPort READ failed');const k=process.env.GEMINI_API_KEY;if(!k)throw Error('Gemini key missing');const gr=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':k},body:JSON.stringify({contents:[{parts:[{text:'Use ONLY this MemoryPort memory. In Indonesian state the owner nickname and preferred answer style. Memory: '+JSON.stringify(mem)}]}]})}),gd=await gr.json();if(!gr.ok)throw Error('Gemini failed '+gr.status);return {rows:mem.length,answer:(gd.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim()}}
async function gpt(access){const k=process.env.OPENAI_API_KEY;if(!k)throw Error('OpenAI key missing');const body={model:'gpt-5.6-luna',input:'Read my MemoryPort memory using memoryport_get_context. Based ONLY on that memory, answer in Indonesian with my nickname and preferred answer style.',tools:[{type:'mcp',server_label:'memoryport',server_description:'Canonical MemoryPort personal memory store',server_url:MCP,authorization:access,require_approval:'never'}],tool_choice:{type:'mcp',server_label:'memoryport',name:'memoryport_get_context'}};const or=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+k},body:JSON.stringify(body)}),od=await or.json();if(!or.ok)throw Error('OpenAI failed '+or.status+': '+(od.error?.message||'unknown'));const calls=(od.output||[]).filter(x=>x.type==='mcp_call'),texts=(od.output||[]).filter(x=>x.type==='message').flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text);if(!calls.some(x=>x.name==='memoryport_get_context'&&x.status==='completed'))throw Error('GPT did not complete MemoryPort MCP read');return {calls:calls.length,answer:texts.join('\n').trim()}}
async function securitySmoke(){const rpc=(headers={},payload={jsonrpc:'2.0',id:1,method:'tools/list'})=>fetch(MCP,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(payload)});const init=await rpc({}, {jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'security-smoke',version:'1'}}});const unauth=await rpc();const invalid=await rpc({authorization:'Bearer invalid-memoryport-security-smoke-token'});const over=await fetch(MCP,{method:'POST',headers:{'content-type':'application/json'},body:'x'.repeat(33000)});const root=await fetch(MCP.replace('/mcp','/'));return {initialize:init.status,unauthorized_tools_list:unauth.status,invalid_bearer:invalid.status,oversized_body:over.status,headers:{x_content_type_options:root.headers.get('x-content-type-options'),referrer_policy:root.headers.get('referrer-policy'),permissions_policy:root.headers.get('permissions-policy'),content_security_policy:root.headers.get('content-security-policy')}}}
http.createServer(async(q,r)=>{const u=new URL(q.url,'http://x');
if(u.pathname==='/')return html(r,200,'<h1>MemoryPort Cross-AI Verifier</h1><p>Isolated verifier. Production MemoryPort core is unchanged.</p><p><a href="/start">Run Gemini READ</a></p><p><a href="/gpt/start">Run GPT READ</a></p>');
if(u.pathname==='/security-smoke'){try{const x=await securitySmoke();console.log('SECURITY_SMOKE_RESULT '+JSON.stringify(x));r.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return r.end(JSON.stringify(x))}catch(e){console.log('SECURITY_SMOKE_ERROR '+e.message);r.writeHead(500,{'content-type':'application/json'});return r.end(JSON.stringify({error:e.message}))}}
if(u.pathname==='/start')return start(q,r,'gemini');if(u.pathname==='/gpt/start')return start(q,r,'gpt');
if(u.pathname==='/callback'||u.pathname==='/gemini/callback'){try{const access=await token(u),x=await gemini(access);return html(r,200,'<h1>Cross-AI READ PASS</h1><p>Provider: Gemini</p><p>Memory rows: '+x.rows+'</p><pre>'+esc(x.answer)+'</pre><p>No token or API key displayed.</p>')}catch(e){return html(r,500,'Test failed: '+esc(e.message))}}
if(u.pathname==='/gpt/callback'){try{const access=await token(u),x=await gpt(access);return html(r,200,'<h1>GPT × MemoryPort READ PASS</h1><p>Completed MCP calls: '+x.calls+'</p><pre>'+esc(x.answer)+'</pre><p>No token or API key displayed.</p>')}catch(e){return html(r,500,'Test failed: '+esc(e.message))}}
return html(r,404,'Not found')}).listen(PORT,()=>console.log('MemoryPort cross-AI verifier listening',PORT));
// security smoke verifier
